#!/bin/bash

if [ -f /opt/openstack-install/compute-installed ] ;then
	echo 'installed'
else
        #controller install 
        sihua-xos-compute-install
        #compute install
        #sihua-xos-install -i eth0 -r compute
        touch /opt/openstack-install/compute-installed
fi
